version: '3.8'

services:
  computer-skills-practice:
    build: .
    ports:
      - "5173:4173"
    volumes:
      - ./server/data:/app/server/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4173/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["npm", "run", "start:prod"]