version: '3.8'

services:
  computer-skills-practice:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./server/data:/app/server/data
    environment:
      - NODE_ENV=production
      - PORT=5173
      # 管理员配置（可选，如果不设置将使用默认值）
      - ADMIN_USERNAME=xtm
      - ADMIN_EMAIL=xtm@tmtec.top
      - ADMIN_PASSWORD=1145141919810
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["npm", "run", "start-public"]